apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  zoo.cfg: |
    tickTime=2000
    dataDir=/data
    clientPort=2181
    initLimit=5
    syncLimit=2
    {{- range $index, $element := .Values.zookeeper.servers }}
    server.{{ $index }}={{ $element }}:2888:3888
    {{- end }}