apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  storageClassName: {{ .Release.Name }}-local-storage
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: {{ .Values.requests.volume.storage }}