apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
spec:
  ports:
    - name: follower
      port: 2888
    - name: leader
      port: 3888
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
