apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 2181
          volumeMounts:
            - name: zookeeper-persistent-storage
              mountPath: /data
          env:
            - name: ZOO_CFG_EXTRA
              value: /conf/zoo.cfg
      volumes:
        - name: zookeeper-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
        - name: config
          configMap:
            name: {{ .Release.Name }}-config