apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: kafka
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 9092
          volumeMounts:
            - name: {{ .Release.Name }}-pvc
              mountPath: /kafka/data
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: {{ .Release.Name }}
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: {{ .Values.kafka.zookeeperConnect }}
            - name: KAFKA_PORT
              value: "9092"
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}