replicaCount: 1

kafka:
  zookeeperConnect: zookeeper:2181

image:
  repository: wurstmeister/kafka
  tag: "latest"

persistence:
  size: 1Gi
  storageClass: hostpath

service:
  type: LoadBalancer
  port: 9092
  targetPort: 9092