# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mysql
  tag: "8.0"

persistence:
  size: 1Gi
  storageClass: hostpath

service:
  type: LoadBalancer
  port: 3306
  targetPort: 3306

mysql:
  rootPassword: "123456"