# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: apache/rocketmq
  tag: "5.3.0"

persistence:
  size: 1Gi
  storageClass: hostpath

service:
  - name: rmqnamesrv
    port: 9876
    targetPort: 9876
  - name: rmqbroker09
    port: 10909
    targetPort: 10909
  - name: rmqbroker11
    port: 10911
    targetPort: 10911
  - name: rmqbroker12
    port: 10912
    targetPort: 10912

rocketmq:
  namesrv:
    max_heap_size: 256M
    heap_newsize: 128M
  rmqbroker:
    max_heap_size: 256M
    heap_newsize: 128M
