# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: redis
  tag: "latest"

persistence:
  size: 1Gi
  storageClass: hostpath

service:
  type: LoadBalancer
  port: 6379
  targetPort: 6379
